// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuBSnXfttTA7zvpzlpzfzOQncAOVmlf8Q',
    appId: '1:673130267805:web:3022409140bac778768074',
    messagingSenderId: '673130267805',
    projectId: 'diractioncourse',
    authDomain: 'diractioncourse.firebaseapp.com',
    databaseURL: 'https://diractioncourse-default-rtdb.firebaseio.com',
    storageBucket: 'diractioncourse.firebasestorage.app',
    measurementId: 'G-XWNM48YDK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8HzdMQ0Dm0VG08GxIcA1HvkrBbhZPShg',
    appId: '1:673130267805:android:5dc07b4a6deea7c3768074',
    messagingSenderId: '673130267805',
    projectId: 'diractioncourse',
    databaseURL: 'https://diractioncourse-default-rtdb.firebaseio.com',
    storageBucket: 'diractioncourse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtmtQ0WxLbHbDBn-nq2z1ksMINIE6OFNw',
    appId: '1:673130267805:ios:b6973c75b463b5e1768074',
    messagingSenderId: '673130267805',
    projectId: 'diractioncourse',
    databaseURL: 'https://diractioncourse-default-rtdb.firebaseio.com',
    storageBucket: 'diractioncourse.firebasestorage.app',
    androidClientId: '673130267805-6cbs4591bu02rha7fikecer8r71h2tn1.apps.googleusercontent.com',
    iosClientId: '673130267805-vc99i2n31054g0058v57nuisah15f8dg.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtmtQ0WxLbHbDBn-nq2z1ksMINIE6OFNw',
    appId: '1:673130267805:ios:b6973c75b463b5e1768074',
    messagingSenderId: '673130267805',
    projectId: 'diractioncourse',
    databaseURL: 'https://diractioncourse-default-rtdb.firebaseio.com',
    storageBucket: 'diractioncourse.firebasestorage.app',
    androidClientId: '673130267805-6cbs4591bu02rha7fikecer8r71h2tn1.apps.googleusercontent.com',
    iosClientId: '673130267805-vc99i2n31054g0058v57nuisah15f8dg.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuBSnXfttTA7zvpzlpzfzOQncAOVmlf8Q',
    appId: '1:673130267805:web:19a88725d7554285768074',
    messagingSenderId: '673130267805',
    projectId: 'diractioncourse',
    authDomain: 'diractioncourse.firebaseapp.com',
    databaseURL: 'https://diractioncourse-default-rtdb.firebaseio.com',
    storageBucket: 'diractioncourse.firebasestorage.app',
    measurementId: 'G-GCP5PPQ12H',
  );
}
